# Generated by Django 4.0.4 on 2022-06-05 02:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, unique, max-255', max_length=255, unique=True, verbose_name='product attribute name')),
                ('description', models.TextField(help_text='format: required')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, unique, max-255', max_length=255, unique=True, verbose_name='nombre de marca')),
                ('is_active', models.BooleanField(default=True, help_text='format: true=brand visible', verbose_name='brand visibility')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max-100', max_length=100, verbose_name='nombre de categoria')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, help_text='format: true=category visible', verbose_name='activo')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category', verbose_name='categoria padre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, unique, max-255', max_length=255, unique=True, verbose_name='tipo de producto')),
                ('is_active', models.BooleanField(default=True, help_text='format: true=product visible', verbose_name='producto activo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='nombre')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscores or hyphens', max_length=255, verbose_name='Slug')),
                ('web_id', models.CharField(help_text='numero de referencia', max_length=50, unique=True, verbose_name='ID Web')),
                ('description', models.TextField(help_text='format: required', verbose_name='descripcion')),
                ('retail_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 9.999.999.99.'}}, help_text='format: maximum price 9.999.999.99', max_digits=9, verbose_name='precio al detalle')),
                ('store_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 9.999.999.99.'}}, help_text='format: maximum price 9.999.999.99', max_digits=9, verbose_name='precio regular')),
                ('percent_discount_price', models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'the value must be between 0 and 99.99.'}}, help_text='format: maximum value 99.99', max_digits=5, null=True, verbose_name='descuento %')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'the price must be between 0 and 9.999.999.99.'}}, help_text='format: maximum price 9.999.999.99', max_digits=9, null=True, verbose_name='precio oferta')),
                ('weight', models.FloatField(verbose_name='peso del producto')),
                ('is_active', models.BooleanField(default=True, help_text='format: true=product visible', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='actualizado')),
                ('attribute', models.ManyToManyField(related_name='attributes', to='products.attribute')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='products.brand')),
                ('category', mptt.fields.TreeManyToManyField(to='products.category', verbose_name='category')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventario.inventory')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type', verbose_name='Product Type')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='format: required, default-default.png', upload_to='images/', verbose_name='imagen')),
                ('alt_text', models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='texto alternativo')),
                ('is_featured', models.BooleanField(default=False, help_text='format: default=false, true=default image', verbose_name='destacado')),
                ('default', models.BooleanField(default=False, help_text='format: default=false, true=default image', verbose_name='por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='creado desde')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='actualizado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='products.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='attribute value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute', to='products.attribute')),
            ],
        ),
    ]
